### ISSUE TITLE
master no longer compiles on Ubuntu 16.04

### ISSUE THREAD

**Issue by bmrzycki** [aarond10/https_dns_proxy#63]
As of sha 03f32858 ( pull request https://github.com/aarond10/https_dns_proxy/pull/62 by @wowczarek ) the following compile error occurs on Ubuntu 16.04:
```
Scanning dependencies of target https_dns_proxy
[ 27%] Building C object CMakeFiles/https_dns_proxy.dir/src/dns_poller.c.o
/home/bmr/git/https_dns_proxy/src/dns_poller.c: In function ‘dns_poller_init’:
/home/bmr/git/https_dns_proxy/src/dns_poller.c:93:11: warning: implicit declaration of function ‘ares_set_servers_ports_csv’ [-Wimplicit-function-declaration]
   if((r = ares_set_servers_ports_csv(d->ares, bootstrap_dns)) != ARES_SUCCESS) {
           ^
...

CMakeFiles/https_dns_proxy.dir/src/dns_poller.c.o: In function `dns_poller_init':
/home/bmr/git/https_dns_proxy/src/dns_poller.c:93: undefined reference to `ares_set_servers_ports_csv'
collect2: error: ld returned 1 exit status
CMakeFiles/https_dns_proxy.dir/build.make:277: recipe for target 'https_dns_proxy' failed
make[2]: *** [https_dns_proxy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/https_dns_proxy.dir/all' failed
make[1]: *** [CMakeFiles/https_dns_proxy.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

The version of c-ares shipped with Ubuntu 16.04 is 1.10.0 and the function call `ares_set_servers_ports_csv()` was added in 1.11.0 ( https://github.com/c-ares/c-ares/commit/7972adc5d7ffa43dd62e675130a0a8d88cbf19a4).

I am able to build by cloning https://github.com/c-ares/c-ares , building tip, and using `LIBRARY_PATH` when running CMake and setting `LD_LIBRARY_PATH` before calling `https_dns_proxy`.

It'd probably be a good idea for either the `README`, or checking `ares_version.h` `ARES_VERSION_MINOR` is 11 or larger when running CMake.

**Comment by aarond10** [comment]
Whoops! I misread the version compatibility when I approved this. (The "ares_set_servers_csv was added in c-ares 1.7.2." statement [here](https://c-ares.haxx.se/ares_set_servers_ports_csv.html)). Now it's in there and as you suggest, I'm inclined to leave it and wait for distro's to catch up unless this starts affecting a lot of people. I'll update the docs.

**Comment by bmrzycki** [comment]
Sounds fair @aarond10 . Thanks for updating the docs.
