### ISSUE TITLE
failed to build with openwrt 19.07-rc1

### ISSUE THREAD

**Issue by laoshaw** [aarond10/https_dns_proxy#70]
https_dns_proxy failed to  compile: error: unknown argument: '-fhonour-copts' [clang-diagnostic-error];

https_dns_proxy-2018-04-23/src/dns_poller.c:4:10: error: 'ares.h' file not found [clang-diagnostic-error]

**Comment by aarond10** [comment]
Not nearly enough context here for me to do anything. What system? What compiler? Do you have ares installed?
